<a href="https://colab.research.google.com/github/OldGuido/AI_Colab/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSORS
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

default data type of float32.

More suitable for deep learning than a numpy array.

In [4]:
import torch
import numpy as np

Lists

In [5]:
sample_list = [[1,2,3,4,5],[6,7,8,9,10]]
sample_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS

In [6]:
np_array = np.random.rand(3,4)
np_array

array([[0.18903044, 0.33100459, 0.35798225, 0.97518822],
       [0.29030184, 0.30269361, 0.3552928 , 0.77782908],
       [0.81617706, 0.53509636, 0.87085704, 0.14890694]])

TENSORS


In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8340, -0.3354, -0.9757, -0.1334],
        [-1.0431, -1.4871,  1.9356, -1.6255],
        [-0.9034,  1.4770, -0.9495, -1.1746]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## create tensor from numpy array
my_tensor = torch.tensor(np_array)
my_tensor

tensor([[0.1890, 0.3310, 0.3580, 0.9752],
        [0.2903, 0.3027, 0.3553, 0.7778],
        [0.8162, 0.5351, 0.8709, 0.1489]], dtype=torch.float64)